### PR TITLE
fix: correctly handle when hot client is false

### LINKED ISSUE #233: Setting hotClient to false results in an error
### System Info

* Operating System: Arch Linux
* Node Version: v10.6.0
* NPM Version: 6.1.0 (using yarn though so 1.8.0)
* webpack Version: 4.16.0
* webpack-serve Version: 2.0.2

### This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### CLI Command

```console
cross-env NODE_ENV=development ts-node ./node_modules/.bin/webpack-serve --config ./webpack.config.ts",

```

##### webpack.config.js

Using typescrypt so it's a webpack.config.ts
https://gist.github.com/Nikki1993/0c0a59af462f2b662446be6d10180255
Check the development object key for dev configuration in question

### Expected Behavior
Settings hotClient disables hot module replacement completely

### Actual Behavior
Setting hotClient results in the following error

```
(node:7176) ExperimentalWarning: The http2 module is an experimental API.
TypeError: Cannot create property 'server' on boolean 'false'
    at WebpackMiddleware.call (/home/nick/git/tieto_eb_client/node_modules/webpack-serve/lib/middleware/WebpackMiddleware.js:26:39)
    at MiddlewareState.call.args (/home/nick/git/tieto_eb_client/node_modules/webpack-serve/lib/middleware/MiddlewareState.js:11:17)
    at /home/nick/git/tieto_eb_client/node_modules/webpack-serve/node_modules/mem/index.js:36:18
    at series (/home/nick/git/tieto_eb_client/node_modules/webpack-serve/lib/app.js:50:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
### How Do We Reproduce?

Supposedly, setting hotClient to false is enough.

P.S. P.S. I created my own types for webpack-serve since supplied one are outdated and haven't had the chance to submit a PR yet.

### PR DESCRIPTION
**Pull request by austince**
Fixes: https://github.com/webpack-contrib/webpack-serve/issues/233
Credit: @shellscape and @Nikki1993

Creating the pull because conversation seems to have dwindled. 

This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [x] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

As noted in #233, the hotClient behavior doesn't match the documentation. One might want the power to manually reload.

### Breaking Changes
None.

### Additional Info
None.

### CODE REVIEW

**Comment by Nikki1993** [comment]
Thank you so much for the PR, my poor head completely forgot about this. My bad.

**Comment by austince** [comment]
No worries @Nikki1993, still doesn't look like it's working :/

**Comment by michael-ciniawsky** [comment]
@austince Follwing the comments this doesn't seem to fix your/the issue atm. What's the current status of this PR :)

**Comment by austince** [comment]
Hi @michael-ciniawsky, yes currently this doesn't work. Followed the initial suggestions on the issue but didn't seem to be the full problem - had to move on to other projects :disappointed: . If I get a chunk of time this week I can look at it again, but not sure!

**Comment by michael-ciniawsky** [comment]
Alright no pressure or anything, but if your decision is to discontinue this please leave a comment or close the PR. Feel free to leave comments when starting to work on a potential fix aswell, so we can try to chime in and help out

**Comment by austince** [comment]
Hi @michael-ciniawksy, I unfortunately don't have time to tackle this. Do you @Nikki1993?

**Comment by Nikki1993** [comment]
I will give it a shot on weekend @austince I've never done tests in js but will try my best :smile:

**Comment by austince** [comment]
Thank you + good luck!

**Comment by alexander-akait** [comment]
FYI, `webpack-serve` will be union with `webpack-dev-server` and deprecated and archived in near future, my recommendation don't use `webpack-serve`, thanks.

**Comment by Nikki1993** [comment]
Oh, that's news to me. Unfortunate.

**Comment by alexander-akait** [comment]
@Nikki1993 this will be done to `webpack@5` and in future we have only one official `dev server` and `CLI` to avoid this misleading

**Comment by austince** [comment]
Can you put that info at the top of the README @evilebottnawi? We recently switched to `webpack-serve` and probably wouldn't have if we knew that was the case. Thank you!

**Comment by alexander-akait** [comment]
@austince :+1: Will do in near future

**Comment by alexander-akait** [comment]
DEPRECATED. Please use `webpack-dev-server` (he is in support and update mode again). Feel free to create a issue if some features are not implemented in `webpack-dev-server`. 

Why deprecated `webpack-serve` ?
- The author stopped developing the package.
- Two development servers are misleading for developers.
- Hard to maintain two packages with same purpose.
- Some `dependencies` are not available to fixes/implement new features/etc (https://www.npmjs.com/package/webpack-hot-client and https://github.com/shellscape/koa-static) and there's nothing we can do here.
- `webpack-dev-server` is stable.

Thanks for using `webpack`! We apologize for the inconvenience. In the future, we will avoid such situations.

**Pull request closed without merging**
