### PR TITLE
Fix no hot

### PR DESCRIPTION
**Pull request by zenflow**
This PR contains a:  **bugfix**

Motivation / Use-Case: Issue #22

### CODE REVIEW

**Comment by shellscape** [comment]
Thanks for the PR! I can spot one or two linting errors in the code. For some reason Circle CI wasn't running on this PR. I think I fixed that on our end. But please run `npm run ci` on your end and that'll run the linter and the tests.

**Comment by shellscape** [comment]
@zenflow ah sorry about this, but it looks like your fork needs to be rebased to master for CI to pass. I was probably merging that PR just as you were cloning the repo. These things happen. Unfortunately I can't rebase your fork from my end, you'll have to handle that.

**Comment by zenflow** [comment]
@shellscape rebased onto master and CI passing :)

**Comment by shellscape** [comment]
Great work, thank you! I'll get this into a 0.1.x release so you can use it.

**Comment by shellscape** [comment]
Your fix has been plublished 🚀

**Pull request merged**
