### PR TITLE
Use modular Lodash imports

### PR DESCRIPTION
**Pull request by billyjanitsch**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [x] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

This is the recommended way to import only the bits of Lodash that you need. (The per-method modules will be [deprecated](https://github.com/lodash/lodash/wiki/Roadmap#v500-2017) entirely in v5.) [Here](https://github.com/tldr-pages/tldr-node-client/issues/185#issue-277212177)'s an explanation. Tl;dr this approach allows the methods to share code, both within this package and elsewhere in the tree, while retaining the benefit of not loading the Lodash monolith.

### Additional Info

🎈

### CODE REVIEW

**Comment by shellscape** [comment]
Thanks for this. They need to get on updating the README on npmjs; https://www.npmjs.com/package/lodash.merge. Had no idea about that deprecation!

Please do remove `package-lock.json` from the PR and we'll get this merged.

**Comment by billyjanitsch** [comment]
Can you clarify why you want package-lock.json removed? I know some people prefer to work without one, but there's currently a package-lock.json on master.

**Comment by shellscape** [comment]
`package-lock.json` causes all manner of nasty merge conflicts, and the maintainers prefer to manage that particular file. It's in the [contributing guidelines](https://github.com/webpack-contrib/webpack-serve/blob/master/CONTRIBUTING.md#pull-requests) and it's not an unreasonable requirement 😄

**Comment by billyjanitsch** [comment]
Ok, I'm happy to remove it! Sorry for missing that contributing requirement.

Just so you know, npm 5.7.x automatically [resolves merge conflicts](https://github.com/npm/npm/releases/tag/v5.7.0) in package-lock.json. You can even use the [official merge driver](https://github.com/npm/npm-merge-driver) to do this automatically when running git commands (on any npm 5.x version)

**Comment by billyjanitsch** [comment]
^ Done. 🙂

**Comment by shellscape** [comment]
Cool, I'll check out the new npm hotness and maybe we can kill that requirement. Thanks for the heads up, and thanks for getting that change in.

**Comment by billyjanitsch** [comment]
No problem! I'm still a little confused about the workflow, though. Now that this patch is merged, the package-lock.json on master is in an invalid state (out of sync with package.json), and running `npm install` will cause it to change.

**Pull request merged**
