### PR TITLE
Apply middleware before starting the server

### PR DESCRIPTION
**Pull request by frenzzy**
This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [x] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

There are no way to apply middleware after calling `listen()` because of koa design

### Breaking Changes

nope, this is just a rollback to how it worked before v2:
https://github.com/webpack-contrib/webpack-serve/blob/v1.0.4/lib/server.js#L126-L139
(`server.listen` goes after `options.add`)

### Additional Info

Trying to fix https://github.com/webpack-contrib/webpack-serve/pull/189#issuecomment-400480707 but this fix does not help with the issue

### CODE REVIEW

**Comment by shellscape** [comment]
Thanks for the PR :beer:

I'm not sure this fixes the issue though, looks like more of a shot in the dark. If it were impossible to add middleware after the server started listening, then none of the tests that request the bundle files would have succeeded. And `server.listen` was blocking any additional middleware from being added, then the middleware called after that move would also not work.

How did you find that this was a koa design problem? Do you have links to documentation?

**Comment by frenzzy** [comment]
Let's see how [`.listen()`](https://github.com/koajs/koa/blob/2.5.1/lib/application.js#L61-L65) in Koa works:
```js
listen(...args) {
  const server = http.createServer(this.callback()); // <= it calls app.callback()
  return server.listen(...args);
}
```
and [`app.callback()`](https://github.com/koajs/koa/blob/2.5.1/lib/application.js#L125-L136) generates a function from configured middlewares and stores it in a closure which makes it impossible to add more middlewares later:
```js
  callback() {
    const fn = compose(this.middleware); // <= no way to modify it after app.callback()

    return (req, res) => {
      const ctx = this.createContext(req, res);
      return this.handleRequest(ctx, fn);
    };
  }
```
And related issues:
- [invalidateMiddleware to be able to change middleware at run-time.](https://github.com/koajs/koa/pull/1075) (declined PR)
- [After app.listen the Application ignores app.use](https://github.com/koajs/koa/issues/321) (old issue)

**Comment by shellscape** [comment]
@frenzzy great info, thanks. What's really strange is that it works as-is right now in the tests, meaning the webpack middleware does get setup because it's retrieving the output bundles correct. https://github.com/webpack-contrib/webpack-serve/blob/5a6e2c83ecb350d4eed59320507fb918ddc0f85e/test/index.test.js#L59-L79 That won't work without setting the special index filename.

Anyhow, to modify this, we'd probably want this instead:

```js
    return promise.then((freePort) => {
      if (typeof options.add === 'function') {
        options.add(app, middleware, options);
      }

      return middleware.webpack.call().then(() => {
        // this function is memo'd, so even if it's called in options.add, we're
        // safe
        middleware.content.call();

        server.listen(freePort, host);
        return server;
      });
    });
```

**Comment by frenzzy** [comment]
Yeay! That fixes the issue! 👍

**Comment by shellscape** [comment]
@frenzzy do you have thoughts on how we can write a test around this? I would like to future-proof that order of operations.

**Comment by frenzzy** [comment]
Maybe modify the test you mentioned above to something like this?
```js
add(app, middleware) { 
  middleware.webpack();
  middleware.content({
    index: 'index.htm', 
  });
  app.use((ctx) => {
    ctx.status = ctx.path === '/output.js' || ctx.path === '/index.htm' ? 403 : 400
  })
},
...
req.get('/index.htm').expect(200),
req.get('/output.js').expect(200), // and not !== /test/fixtures/htm/output.js
req.get('/random').expect(400),
```

**Comment by shellscape** [comment]
What was that last commit? 4407ccd doesn't look good, please roll that back so the code in `app.js` looks like the block I pasted above. to avoid commit lint issues in CI, please use the angular commit format: https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits

**Comment by shellscape** [comment]
@frenzzy you can ignore the `TypeError: Cannot read property 'port' of null` failing test, as that happens periodically. but the other test is failing. probably best to get that working locally. https://circleci.com/gh/webpack-contrib/webpack-serve/949

**Comment by frenzzy** [comment]
`TypeError: Cannot read property 'port' of null` is failing because `server.listen` is asynchronous in according to node.js documentation:
> [`server.listen([port][, hostname][, backlog][, callback])`](https://nodejs.org/dist/latest-v6.x/docs/api/http.html#http_server_listen_handle_callback)
> This function is asynchronous. callback will be added as a listener for the 'listening' event.

So, I think we should wait until server is actually listening before resolving the promise, don't you think? It fixes failing test btw, because `app.server.address()` may return `null` when server is not listening yet.

Also `req.get('/output.js')` still does not return the js file as expected, don't know why...

**Comment by shellscape** [comment]
Please leave the `TypeError: Cannot read property 'port' of null` alone for now. It's outside of the scope of this PR and part of a different fix.

The 204 test is probably failing because `middleware.webpack` hasn't finished it's promise before `webpack.content` is called in the `add` method of the test. You'll probably have to mimic the code in `app.js` in the test.

**Comment by frenzzy** [comment]
Thanks! Looks like works now

**Comment by frenzzy** [comment]
Closing because it was fixed in 5e0c195

**Comment by shellscape** [comment]
@frenzzy ah I didn't mean to snipe this from you. I had to implement the serial promises because of another issue I found. I think we should reopen this and make the tests great around the change.

**Comment by frenzzy** [comment]
That is fine, no worries! I think it is just faster if you create a commit yourself with tests rather than telling me how to write them properly and wait :)
Feel free to copy&paste code from the PR if it is useful.

**Comment by shellscape** [comment]
Great, thanks. I think the test idea you had was the right direction.

**Pull request closed without merging**
